TAMUChineseSchool_new/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :teachers
  resources :courses

end

TAMUChineseSchool_new/app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :teacher
end

TAMUChineseSchool_new/app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :course, dependent: :destroy
  belongs_to :user

  def fullname

    User.find(user_id).fullname


  end
end

TAMUChineseSchool_new/app/models/user.rb
class User < ActiveRecord::Base
  has_many :teachers, dependent: :destroy

  def fullname
    first_name+" "+last_name
  end
end

TAMUChineseSchool_new/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
    @courses=Course.all
    @teachers=Teacher.all
  end

  def create
    @course = Course.new(course_params)

    @course.save
    redirect_to @course
  end

  def show
    redirect_to action: "index"
  end

  def index
    @courses = Course.all
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course).permit(:year, :semester,:name,:class_room,:time,:textbook, :teacher_id, :course_discription)
  end

end

TAMUChineseSchool_new/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
    if request.get?
      session[:user_id] = nil
      @user = User.new
    else
      @user = User.new(params[:user])
      logged_in_user = @user.try_to_login

      if logged_in_user
        session[:user_id] = logged_in_user.id
        redirect_to(:action => "index")
      else
        # flash[:notice] = "Invalid user/password combination"
        redirect_to(:action => "loginFail")
      end
    end
  end

  def show
    redirect_to(:action => "login")
  end

  def loginFail

  end
  #清空登录信息
  def reset
    params[:user]["username"]=null
    params[:user]["hashed_password"]=null
  end
end

TAMUChineseSchool_new/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def new
    @users=User.all
    #@data = 1
  end

  def create
    @teacher = Teacher.new(user_id: params[:teacher][:user_id])

    @teacher.save
    redirect_to @teacher
  end

#  def create
#    @post = Post.find(params[:post_id])
#    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
#    redirect_to post_path(@post)
#  end

  def show
    redirect_to action: "index"
  end

  def index
    @teachers = Teacher.all
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    redirect_to teachers_path
  end

end

TAMUChineseSchool_new/app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to account_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to new_user_session_url
  end


end

TAMUChineseSchool_new/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)

    @user.save
    redirect_to @user
  end

  def show
    redirect_to action: "index"
#    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(
          :first_name, :last_name, :first_name_chn, :last_name_chn,
          :gender, :address, :phone, :email )
    end
end

TAMUChineseSchool_new/app/helpers/courses_helper.rb
module CoursesHelper
end

TAMUChineseSchool_new/app/helpers/login_helper.rb
module LoginHelper
end

TAMUChineseSchool_new/app/helpers/teachers_helper.rb
module TeachersHelper
end

TAMUChineseSchool_new/app/helpers/user_session_helper.rb
module UserSessionHelper
end

TAMUChineseSchool_new/app/helpers/users_helper.rb
module UsersHelper
end

TAMUChineseSchool_new/app/views/courses/index.html.erb
<h1>Listing all courses</h1>

<%= link_to 'New course', new_course_path %>
<br><br>

<table>
  <tr>
    <th>Year</th>
    <th>Semester</th>
    <th>Name</th>
    <th>Classroom</th>
    <th>Time</th>
    <th>Textbook</th>
    <th>Teacher</th>
    <th>Description</th>
  </tr>

  <% @courses.each do |course| %>
      <tr>
        <td><%= course.year %></td>
        <td><%= course.semester %></td>
        <td><%= course.name %></td>
        <td><%= course.class_room %></td>
        <td><%= course.time %></td>
        <td><%= course.textbook %></td>
        <td><%= course.teacher.fullname %></td>
        <td><%= course.course_discription %></td>

        <td><%= link_to 'Show', course_path(course) %></td>
        <td><%= link_to 'Delete', course_path(course),
                        method: :delete, data: { confirm: 'Are you sure to delete?'}%></td>

      </tr>
  <% end %>
</table>

TAMUChineseSchool_new/app/views/courses/new.html.erb
<%= form_for :course, url: courses_path do |f| %>
    <table>
      <tr>
        <td> <%= f.label :year %></td>
        <td><%= f.text_field :year %></td>
      </tr>

      <tr>
        <td><%= f.label :semester %></td>
        <td><%= f.select :semester, ['Spring', 'Fall'] %></td>

      </tr>

      <tr>
        <td><%= f.label :name %></td>
        <td><%= f.text_area :name %></td>
      </tr>
      <tr>
        <td><%= f.label :class_room %></td>
        <td><%= f.text_area :class_room %></td>
      </tr>

      <tr>
        <td><%= f.label :time %></td>
        <td>
          <%= time_select("ar", "we", prompt: {hour: 'Choose hour', minute: 'Choose minute', second: 'Choose seconds'}) %> --
          <%= time_select("article", "written_on", prompt: {hour: 'Choose hour', minute: 'Choose minute', second: 'Choose seconds'}) %></td>
      </tr>

      <tr>
        <td><%= f.label :textbook %></td>
        <td><%= f.text_field :textbook %></td>
      </tr>

      <tr>
        <td><%= f.label :teacher %></td>

        <td> <%= f.select :teacher_id, @teachers.map {|r| [r.fullname,r.id] } %></td>
      </tr>

      <tr>
        <td><%= f.label :course_discription %></td>
        <td><%= f.text_area :course_discription %></td>
      </tr>

    </table>

    <p>
      <%= f.submit value="Add Course" %>
    </p>

<% end %>

TAMUChineseSchool_new/app/views/login/index.html.erb
h1>Choose a page to look!</h1>

<p><%= link_to 'Users', :controller=>"users",:action=>"index" %></p>


<p><%= link_to 'Logout', :controller=>"login",:action=>"login"%></p>  "</p>

TAMUChineseSchool_new/app/views/login/login.html.erb
<h1>Welcome to login!</h1>
<% form_tag do %>
    <table>
      <tr>
        <td>User name:</td>
        <td><%= text_field("user", "username") %></td>
      </tr>
      <tr>
        <td>Password:</td>
        <td><%= password_field("user", "hashed_password") %></td>
      </tr>
      <tr>
        <td></td>
        <td><input type="submit" value=" login " /> <input type="reset" value=" reset " /></td>
      </tr>
    </table>
<% end %>

TAMUChineseSchool_new/app/views/login/loginFail.html.erb
<h1>Invalid user/password combination</h1>
<%form_tag do%>
    <%= link_to 'Back', :action=>"login" %>
<%end%>

TAMUChineseSchool_new/app/views/users/index.html.erb
<h1>Listing all users</h1>

<%= link_to 'New user', new_user_path %>
<br><br>

<table>
  <tr>
    <th>Last Name</th>
    <th>Last Name Chinese</th>
    <th>First Name</th>
    <th>First Name Chinese</th>
    <th>Gender</th>
    <th>Address</th>
    <th>Phone</th>
    <th>EMail</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.last_name %></td>
      <td><%= user.last_name_chn %></td>
      <td><%= user.first_name %></td>
      <td><%= user.first_name_chn %></td>
      <td><%= user.gender %></td>
      <td><%= user.address %></td>
      <td><%= user.phone %></td>
      <td><%= user.email %></td>

      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Delete', user_path(user),
                                 method: :delete, data: { confirm: 'Are you sure to delete?'}%></td>

    </tr>
  <% end %>
</table>

TAMUChineseSchool_new/app/views/users/new.html.erb
<%= form_for :user, url: users_path  do |f| %>
    <p>
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </p>

    <p>
      <%= f.label :last_name_chn %><br>
      <%= f.text_field :last_name_chn %>
    </p>

    <p>
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </p>

    <p>
      <%= f.label :first_name_chn %><br>
      <%= f.text_field :first_name_chn %>
    </p>

    <p>
        <%= f.select :gender, ['Male', 'Female'] %>
    </p>

    <p>
      <%= f.label :address %><br>
      <%= f.text_area :address %>
    </p>

    <p>
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

TAMUChineseSchool_new/app/views/users/show.html.erb
<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Last Name Chinese:</strong>
  <%= @user.last_name_chn %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>First Name Chinese:</strong>
  <%= @user.first_name_chn %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>EMail:</strong>
  <%= @user.email %>
</p>