TAMUChineseSchool_final_final/config/routes.rb
Rails.application.routes.draw do
  #mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users

  devise_for :courses
  resources :families
  resources :courses
  resources :events


  get 'about' => 'about#index'
  get 'organization' => 'organization#index'
  get 'school_rules' => 'school_rules#index'
  get 'teachers_guidelines' => 'teachers_guidelines#index'
  get 'students_handbook' => 'students_handbook#index'
  get 'contact' => 'contact#index'
  resources :contact
  resources :taking_courses
end

TAMUChineseSchool_final_final/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

TAMUChineseSchool_final_final/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

TAMUChineseSchool_final_final/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% event_title = 'Events' %>
<% course_title = 'Courses' %>
<% if user_signed_in? %>
    <% if current_user.admin? %>

        <% event_title = 'Event management' %>
        <% course_title = 'Course management' %>
    <% end %>
<% end %>
<li><%= link_to course_title, courses_path %></li>

<% if user_signed_in? %>
    <% if current_user.admin? %>
        <!--
    <li><%= link_to 'Admin', '/admin' %></li>
-->
        <li><%= link_to 'User management', users_path %></li>
    <% end %>
<% end %>

<% if user_signed_in? %>

    <li><%= link_to 'My children', families_path %></li>

    <li> <%= link_to event_title, events_path %> </li>


    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
    <li> <%= link_to event_title, events_path %> </li>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

  <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact Us', contact_path %></li>

TAMUChineseSchool_final_final/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TAMU Chinese School" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "TAMU Chinese School" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'framework', 'data-turbolinks-track' => true %> 
    <%= stylesheet_link_tag 'index', 'data-turbolinks-track' => true %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery.slidepanel.setup', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery.tabs.setup', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery.ui.min', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>